version: '3'
services:
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sample
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      TZ: "UTC"
    container_name: 'sample-postgres'
    command: postgres -c listen_addresses='*'