spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase/xml/db.changelog.xml
    default-schema: public
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG